# Generated by Django 5.2.16 on 2026-07-31 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxpayerOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_id', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('legal_name', models.CharField(max_length=200, verbose_name='Razón social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de fantasía')),
                ('is_active', models.BooleanField(default=True)),
                ('dte_39_enabled', models.BooleanField(default=False, verbose_name='DTE 39 declarado')),
                ('dte_41_enabled', models.BooleanField(default=False, verbose_name='DTE 41 declarado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ORGANIZATION_ADMIN', 'Administrador de organización'), ('ACCOUNTANT', 'Contadora/or'), ('OPERATOR', 'Operador/a'), ('VIEWER', 'Solo lectura')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.taxpayerorganization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='uq_membership_org_user')],
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('ORGANIZATION_ADMIN', 'Administrador de organización'), ('ACCOUNTANT', 'Contadora/or'), ('OPERATOR', 'Operador/a'), ('VIEWER', 'Solo lectura')], max_length=32)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('EXPIRED', 'Expirada'), ('REVOKED', 'Revocada')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='organizations.taxpayerorganization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organization', 'email'), name='uq_pending_invitation_org_email')],
            },
        ),
    ]
