# Generated by Django 5.2.16 on 2026-07-31 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiiProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('DISABLED', 'Deshabilitado'), ('CERTIFICATION', 'Certificación')], default='DISABLED', max_length=16)),
                ('productive_issuance_enabled', models.BooleanField(default=False, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sii_profile', to='organizations.taxpayerorganization')),
            ],
        ),
        migrations.CreateModel(
            name='SiiSubmissionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PREPARED', 'Preparado'), ('SUBMITTING', 'Enviando'), ('UNCERTAIN', 'Incierto'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], max_length=16)),
                ('track_id', models.CharField(blank=True, max_length=120)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sii_attempts', to='organizations.taxpayerorganization')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_attempts', to='documents.electronicreceipt')),
            ],
        ),
    ]
