# Generated by Django 5.2.16 on 2026-08-01 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sales', '0002_alter_sale_reconciliation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='Primer día del período')),
                ('parser_version', models.CharField(max_length=40)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='private/imports/%Y/%m/')),
                ('file_hash', models.CharField(max_length=64)),
                ('file_size', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('UPLOADED', 'Cargado'), ('VALIDATED', 'Validado'), ('BLOCKED', 'Bloqueado'), ('COMMITTED', 'Confirmado'), ('FAILED', 'Fallido')], default='UPLOADED', max_length=16)),
                ('detected_rows', models.PositiveIntegerField(default=0)),
                ('new_rows', models.PositiveIntegerField(default=0)),
                ('existing_rows', models.PositiveIntegerField(default=0)),
                ('conflict_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('ignored_rows', models.PositiveIntegerField(default=0)),
                ('taxable_rows', models.PositiveIntegerField(default=0)),
                ('exempt_rows', models.PositiveIntegerField(default=0)),
                ('total_net', models.PositiveBigIntegerField(default=0)),
                ('total_vat', models.PositiveBigIntegerField(default=0)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('declared_net', models.PositiveBigIntegerField(blank=True, null=True)),
                ('declared_vat', models.PositiveBigIntegerField(blank=True, null=True)),
                ('declared_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='organizations.taxpayerorganization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('original_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('classification', models.CharField(blank=True, max_length=16)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('NEW', 'Nueva'), ('ALREADY_IMPORTED', 'Ya importada'), ('CONFLICT', 'Conflicto'), ('ERROR', 'Error'), ('IGNORED', 'Ignorada'), ('IMPORTED', 'Importada')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='imports.importbatch')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='documents.electronicreceipt')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='sales.sale')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'file_hash'), name='uq_import_batch_org_hash'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'line_number'), name='uq_import_row_line'),
        ),
    ]
