# Generated by Django 5.2.16 on 2026-07-31 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='Primer día del mes')),
                ('version', models.PositiveIntegerField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='monthly_books/%Y/%m/')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('total_net', models.PositiveBigIntegerField(default=0)),
                ('total_vat', models.PositiveBigIntegerField(default=0)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('second_category_withholding', models.PositiveBigIntegerField(default=0, verbose_name='Retención segunda categoría')),
                ('ppm', models.PositiveBigIntegerField(default=0, verbose_name='PPM manual')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('HAS_EXCEPTIONS', 'Con excepciones'), ('READY_TO_CLOSE', 'Listo para cerrar'), ('CLOSED', 'Cerrado'), ('REOPENED', 'Reabierto')], default='OPEN', max_length=24)),
                ('reopen_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes', to='organizations.taxpayerorganization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'period', 'version'), name='uq_close_org_period_version')],
            },
        ),
    ]
