# Generated by Django 5.2.16 on 2026-07-31 18:08

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.PositiveSmallIntegerField(choices=[(39, 'Boleta electrónica afecta'), (41, 'Boleta electrónica exenta')])),
                ('folio', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tax_issue_date', models.DateField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('net_amount', models.PositiveBigIntegerField(default=0)),
                ('vat_amount', models.PositiveBigIntegerField(default=0)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('issuer_name', models.CharField(blank=True, max_length=200)),
                ('signer_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('NOT_CREATED', 'No creada'), ('PREPARED', 'Preparada'), ('SUBMITTING', 'Enviando'), ('UNCERTAIN', 'Estado incierto'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('CANCELLATION_PENDING', 'Anulación pendiente'), ('CANCELLED', 'Anulada')], default='NOT_CREATED', max_length=24)),
                ('track_id', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='organizations.taxpayerorganization')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='sales.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('folio__isnull', False)), fields=('organization', 'document_type', 'folio'), name='uq_receipt_org_type_folio'), models.CheckConstraint(condition=models.Q(('net_amount', django.db.models.expressions.CombinedExpression(models.F('total_amount'), '-', models.F('vat_amount')))), name='receipt_net_plus_vat_total'), models.CheckConstraint(condition=models.Q(('document_type', 39), ('vat_amount', 0), _connector='OR'), name='receipt_dte41_vat_zero')],
            },
        ),
    ]
