# Generated by Django 5.2.16 on 2026-07-31 18:08

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_date', models.DateField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(max_length=500)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_tax_id', models.CharField(blank=True, max_length=12)),
                ('observations', models.TextField(blank=True)),
                ('tax_classification', models.CharField(choices=[('TAXABLE', 'Afecta'), ('EXEMPT', 'Exenta')], max_length=16)),
                ('net_amount', models.PositiveBigIntegerField()),
                ('vat_amount', models.PositiveBigIntegerField()),
                ('total_amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('READY', 'Lista'), ('DOCUMENTED', 'Documentada'), ('OBSERVED', 'Observada'), ('CANCELLED', 'Anulada')], default='READY', max_length=16)),
                ('reconciliation_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RECONCILED', 'Conciliada'), ('AMOUNT_DIFFERENCE', 'Diferencia de monto'), ('POSSIBLE_DUPLICATE', 'Posible duplicado'), ('CLASSIFICATION_CONFLICT', 'Conflicto de clasificación'), ('CORRECTION_REQUIRED', 'Requiere corrección')], default='PENDING', max_length=32)),
                ('origin_system', models.CharField(default='MANUAL', max_length=80)),
                ('external_id', models.CharField(max_length=160)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='organizations.taxpayerorganization')),
            ],
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_amount', models.PositiveBigIntegerField()),
                ('total_amount', models.PositiveBigIntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.sale')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0), ('vat_amount__gte', 0), ('total_amount__gt', 0)), name='sale_positive_amounts'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount', django.db.models.expressions.CombinedExpression(models.F('total_amount'), '-', models.F('vat_amount')))), name='sale_net_plus_vat_total'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('tax_classification', 'TAXABLE'), ('vat_amount', 0), _connector='OR'), name='sale_exempt_vat_zero'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('organization', 'origin_system', 'external_id'), name='uq_sale_org_origin_external'),
        ),
    ]
