# Generated by Django 5.2.16 on 2026-08-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='reconciliation_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RECONCILED', 'Conciliada'), ('AMOUNT_DIFFERENCE', 'Diferencia de monto'), ('POSSIBLE_DUPLICATE', 'Posible duplicado'), ('CLASSIFICATION_CONFLICT', 'Conflicto de clasificación'), ('CORRECTION_REQUIRED', 'Requiere corrección'), ('MISSING_PAYMENT_DATA', 'Faltan datos del pago')], default='PENDING', max_length=32),
        ),
    ]
